#!/bin/sh

case "$1" in
    start)
        start-stop-daemon -S --startas /usr/bin/aesdsocket -- -d
        ;;
    stop)
        start-stop-daemon -K --signal SIGTERM --exec /usr/bin/aesdsocket
        ;;
esac

exit 0
